// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqHx7B7I5XoBlz__hMQFIYl0EVUQBfUqw',
    appId: '1:794454592907:web:157b9b74b9bd208463738e',
    messagingSenderId: '794454592907',
    projectId: 'kelompok-todolist-22a17',
    authDomain: 'kelompok-todolist-22a17.firebaseapp.com',
    storageBucket: 'kelompok-todolist-22a17.firebasestorage.app',
    measurementId: 'G-EB5QPCVN2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_1OBUgCbEloeAHoJoxzwEbYiegRwS_3Q',
    appId: '1:794454592907:android:8b6813de4212199063738e',
    messagingSenderId: '794454592907',
    projectId: 'kelompok-todolist-22a17',
    storageBucket: 'kelompok-todolist-22a17.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqHx7B7I5XoBlz__hMQFIYl0EVUQBfUqw',
    appId: '1:794454592907:web:6dc0784e776f716463738e',
    messagingSenderId: '794454592907',
    projectId: 'kelompok-todolist-22a17',
    authDomain: 'kelompok-todolist-22a17.firebaseapp.com',
    storageBucket: 'kelompok-todolist-22a17.firebasestorage.app',
    measurementId: 'G-ZBB9ZP195W',
  );
}
